"""
Скрипт сборки EmailSenderPro в .exe через PyInstaller.
Использование: python build.py [--onefile] [--clean]
"""
import os
import sys
import shutil
import argparse
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent
DIST = ROOT / "dist"
BUILD = ROOT / "build"
SPEC_FILE = ROOT / "EmailSenderPro.spec"

APP_NAME = "EmailSenderPro"
APP_VERSION = "1.0.0"
ICON_PATH = ROOT / "assets" / "icons" / "app.ico"


def run(cmd: list, cwd: Path = None) -> int:
    print(f"\n→ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd or ROOT)
    return result.returncode


def generate_spec(onefile: bool = False) -> str:
    """Генерирует .spec файл для PyInstaller."""
    sep = os.pathsep

    binaries = ""
    # Добавляем Qt WebEngine ресурсы (Windows)
    qt_data = ""

    icon_param = f"'{ICON_PATH}'" if ICON_PATH.exists() else "None"

    exe_type = "EXE" if onefile else "EXE"
    collect_type = "COLLECT" if not onefile else ""

    return f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py

block_cipher = None

a = Analysis(
    ['{ROOT / "main.py"}'],
    pathex=['{ROOT}'],
    binaries=[],
    datas=[
        ('{ROOT / "assets"}', 'assets'),
        ('{ROOT / "i18n"}', 'i18n'),
        ('{ROOT / "data"}', 'data'),
    ],
    hiddenimports=[
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtSvgWidgets',
        'PyQt6.QtPrintSupport',
        'aiosmtplib',
        'cryptography',
        'jwt',
        'dns.resolver',
        'dns.rdatatype',
        'openpyxl',
        'chardet',
        'certifi',
        'html2text',
        'reportlab',
        'reportlab.platypus',
        'reportlab.lib',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'pandas', 'scipy'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    {"a.binaries, a.zipfiles, a.datas," if onefile else "[],"  }
    {"a.binaries, a.datas," if not onefile else ""}
    name='{APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon={icon_param},
    onefile={onefile},
    version='version_info.txt',
)
{"" if onefile else f"""
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    name='{APP_NAME}',
)"""}
"""


def generate_version_info():
    """Генерирует файл версии Windows для PyInstaller."""
    content = f"""# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(1, 0, 0, 0),
    prodvers=(1, 0, 0, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'EmailSenderPro'),
         StringStruct(u'FileDescription', u'Email Sender Pro — Professional Email Marketing'),
         StringStruct(u'FileVersion', u'{APP_VERSION}'),
         StringStruct(u'InternalName', u'{APP_NAME}'),
         StringStruct(u'LegalCopyright', u'Copyright 2024'),
         StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
         StringStruct(u'ProductName', u'Email Sender Pro'),
         StringStruct(u'ProductVersion', u'{APP_VERSION}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)"""
    with open(ROOT / "version_info.txt", "w") as f:
        f.write(content)
    print("✓ version_info.txt создан")


def create_icon_placeholder():
    """Создаёт заглушку иконки если нет ICO файла."""
    icons_dir = ROOT / "assets" / "icons"
    icons_dir.mkdir(parents=True, exist_ok=True)
    ico_path = icons_dir / "app.ico"
    if not ico_path.exists():
        print("⚠ app.ico не найден — создайте иконку 256x256 в assets/icons/app.ico")


def clean():
    """Очищает директории сборки."""
    for d in [DIST, BUILD]:
        if d.exists():
            shutil.rmtree(d)
            print(f"✓ Удалена директория: {d}")
    if SPEC_FILE.exists():
        SPEC_FILE.unlink()
        print(f"✓ Удалён spec файл: {SPEC_FILE}")
    vi = ROOT / "version_info.txt"
    if vi.exists():
        vi.unlink()


def check_requirements():
    """Проверяет наличие PyInstaller."""
    try:
        import PyInstaller
        print(f"✓ PyInstaller {PyInstaller.__version__}")
    except ImportError:
        print("✗ PyInstaller не установлен. Устанавливаю...")
        run([sys.executable, "-m", "pip", "install", "pyinstaller"])


def build(onefile: bool = False):
    """Выполняет сборку приложения."""
    print(f"\n{'='*60}")
    print(f"  Email Sender Pro v{APP_VERSION} — сборка")
    print(f"  Режим: {'One-file EXE' if onefile else 'Папка'}")
    print(f"{'='*60}\n")

    check_requirements()
    create_icon_placeholder()
    generate_version_info()

    # Записываем .spec
    spec_content = generate_spec(onefile)
    with open(SPEC_FILE, "w") as f:
        f.write(spec_content)
    print(f"✓ {SPEC_FILE.name} создан")

    # Запускаем PyInstaller
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--clean",
        "--noconfirm",
        str(SPEC_FILE),
    ]

    code = run(cmd)
    if code != 0:
        print(f"\n✗ Сборка завершилась с ошибкой (код {code})")
        sys.exit(code)

    print("\n" + "="*60)
    print(f"✓ Сборка успешна!")
    if onefile:
        exe = DIST / f"{APP_NAME}.exe"
        if exe.exists():
            size_mb = exe.stat().st_size / 1024 / 1024
            print(f"✓ Файл: {exe}")
            print(f"✓ Размер: {size_mb:.1f} MB")
    else:
        out_dir = DIST / APP_NAME
        print(f"✓ Папка: {out_dir}")
    print("="*60 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Email Sender Pro Builder")
    parser.add_argument("--onefile", action="store_true",
                        help="Собрать в один .exe файл (медленнее запускается)")
    parser.add_argument("--clean", action="store_true",
                        help="Очистить папки сборки перед компиляцией")
    args = parser.parse_args()

    if args.clean:
        clean()

    build(onefile=args.onefile)
