; ═══════════════════════════════════════════════════════════════════
;  Email Sender Pro — Inno Setup 6  (Aether Dark branded installer)
; ═══════════════════════════════════════════════════════════════════

#define MyAppName      "Email Sender Pro"
#define MyAppVersion   "1.0.0"
#define MyAppPublisher "FTPLabs"
#define MyAppURL       "https://emailsenderpro.app"
#define MyAppExeName   "EmailSenderPro.exe"
#define BuildDir       "..\dist\EmailSenderPro"

[Setup]
AppId={{A7B3C9D2-1E4F-5A8B-9C0D-2E3F4A5B6C7D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\EmailSenderPro
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
AllowNoIcons=no
; --- Aether Dark branded images (generated by create_wizard_bitmaps.py) ---
WizardStyle=modern
WizardSizePercent=120,110
WizardImageFile=wizard_sidebar.bmp
WizardSmallImageFile=wizard_header.bmp
OutputDir=..\dist\installer
OutputBaseFilename=EmailSenderPro-{#MyAppVersion}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes
MinVersion=10.0
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#BuildDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}";          Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Удалить {#MyAppName}";  Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}";    Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{userappdata}\EmailSenderPro\cache"
Type: filesandordirs; Name: "{userappdata}\EmailSenderPro\logs"

[Registry]
Root: HKCU; Subkey: "Software\FTPLabs\EmailSenderPro"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\FTPLabs\EmailSenderPro"; ValueType: string; ValueName: "Version"; ValueData: "{#MyAppVersion}"

[Code]
// Aether Dark palette — Inno Setup uses BGR hex (reverse of #RRGGBB)
// #070711 -> $110707 | #131426 -> $261413 | #8B5CF6 -> $F65C8B | #F0F0FA -> $FAF0F0

procedure ApplyAetherDark();
var
  i: Integer;
begin
  // Main wizard window
  WizardForm.Color      := $110707;
  WizardForm.Font.Color := $FAF0F0;

  // Page name label (header title) — exists in both classic and modern
  if WizardForm.PageNameLabel <> nil then begin
    WizardForm.PageNameLabel.Font.Color := $FAF0F0;
    WizardForm.PageNameLabel.Font.Style := [fsBold];
  end;

  // Style buttons, checkboxes, listboxes by class name
  for i := 0 to WizardForm.ComponentCount - 1 do begin
    if WizardForm.Components[i].ClassNameIs('TNewButton') then begin
      TNewButton(WizardForm.Components[i]).Color      := $F65C8B;
      TNewButton(WizardForm.Components[i]).Font.Color := $FAF0F0;
    end;
    if WizardForm.Components[i].ClassNameIs('TNewCheckBox') then
      TNewCheckBox(WizardForm.Components[i]).Font.Color := $C09090;
    if WizardForm.Components[i].ClassNameIs('TNewListBox') then begin
      TNewListBox(WizardForm.Components[i]).Color      := $261413;
      TNewListBox(WizardForm.Components[i]).Font.Color := $FAF0F0;
    end;
    if WizardForm.Components[i].ClassNameIs('TNewEdit') then begin
      TNewEdit(WizardForm.Components[i]).Color      := $261413;
      TNewEdit(WizardForm.Components[i]).Font.Color := $FAF0F0;
    end;
  end;
end;

procedure InitializeWizard();
begin
  ApplyAetherDark();
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  ApplyAetherDark();
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
end;

function GetUninstallString(): String;
var
  sPath, sStr: String;
begin
  sPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#emit SetupSetting("AppId")}_is1');
  sStr  := '';
  if not RegQueryStringValue(HKLM, sPath, 'UninstallString', sStr) then
    RegQueryStringValue(HKCU, sPath, 'UninstallString', sStr);
  Result := sStr;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  sStr: String;
  iCode: Integer;
begin
  if (CurStep = ssInstall) and (GetUninstallString() <> '') then begin
    sStr := RemoveQuotes(GetUninstallString());
    Exec(sStr, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iCode);
  end;
end;
